services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-service
    hostname: blog-service
    ports:
      - "7141:7141"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7141
      - ConnectionStrings__DefaultConnection=Server=blog-db;Port=5432;Database=blogdb;User Id=postgres;Password=1;
    depends_on:
      - blog-db
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - blog-net


  blog-db:
    image: postgres:17
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - blog-net
  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ax@micro.kz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7313:80"
    networks:
      - blog-net


  nginx:
    image: nginx:latest
    container_name: blog-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wwwroot:/var/www/blog/wwwroot:ro
    depends_on:
      - minio
      - blog-service
    networks: 
      - blog-net


  minio:
    image: minio/minio
    container_name: blog-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports: 
      - "9000:9000" 
      - "9001:9001"
    networks: 
      - blog-net

networks: 
  blog-net: 
    driver: bridge
    
volumes:
  blog_db_data:
  minio_data:
