services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-service
    hostname: blog-service
    ports:
      - "7141:7141"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7141
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ConnectionStrings__DefaultConnection=Server=blog-db;Port=5432;Database=blogdb;User Id=postgres;Password=1;
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - blog-db
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  blog-db:
    image: postgres:17
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ax@micro.kz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7313:80"

volumes:
  blog_db_data:
